### PR TITLE
Fix interdependency issue

### PR DESCRIPTION
**Pull request by YoruNoHikage**
I wanted to use denormalizr in my project but my schemas are all interdependent leading to a "Too much recursion" error. I wrote this test to see if it can handle a simple use case but I have no solution for this.

### CODE REVIEW

**Comment by gpbl** [comment]
Interesting, thanks! How should recursive schemas be denormalized? Could you just denormalize without the nested `articles`?

**Comment by YoruNoHikage** [comment]
Ideally, you could do something like this after denormalization : `denormalized.author.articles[0].author.articles[0]...`. I think the solution may be to keep references into a bag (just like normalizr do), adding every dependency the object have.

**Comment by gpbl** [comment]
I see what you mean. However now I've not the time to work on this 😓 would you try to send a PR?

**Comment by YoruNoHikage** [comment]
I'll give it a try. :)

**Comment by gpbl** [comment]
This would be awesome ☺️

**Comment by YoruNoHikage** [comment]
Added in my project, seems to work well. :)
Code could be simplified I guess.

**Comment by gpbl** [comment]
Looks great! Thanks a lot :+1:

**Comment by gpbl** [comment]
Published as v0.0.8 ^_^

**Comment by YoruNoHikage** [comment]
Hooray :fireworks:

**Pull request merged**
